# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
import torch

a = torch.rand(7,7)
a

# Create random tensor


tensor([[0.0120, 0.8221, 0.4094, 0.3023, 0.5309, 0.5230, 0.6358],
        [0.2902, 0.1498, 0.9457, 0.0504, 0.6050, 0.0367, 0.7353],
        [0.7575, 0.0485, 0.4776, 0.1673, 0.2836, 0.3550, 0.4991],
        [0.9077, 0.8878, 0.9877, 0.5820, 0.7941, 0.6292, 0.3127],
        [0.7662, 0.0232, 0.8726, 0.1997, 0.8049, 0.8482, 0.7641],
        [0.3798, 0.5618, 0.4456, 0.8109, 0.6427, 0.1089, 0.4602],
        [0.1147, 0.2600, 0.3204, 0.0584, 0.9997, 0.8500, 0.2930]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
b=torch.rand(1,7)
a@b.T
# Perform matrix multiplication 


tensor([[1.5416],
        [1.4945],
        [1.2077],
        [2.0729],
        [2.0830],
        [1.6890],
        [1.1926]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
a = torch.rand(7,7)
torch.manual_seed(0)
b = torch.rand(1,7)


# Matrix multiply tensors
torch.matmul(a,b.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed(0)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [8]:
# Set random seed
torch.manual_seed(1234)
a = torch.rand(7,7,device='cuda')
torch.manual_seed(1234)
b = torch.rand(1,7,device='cuda')

# Check for access to GPU

# Create two random tensors on GPU
a,b

(tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
         [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
         [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
         [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
         [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
         [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
         [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
        device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903]],
        device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
c=a@b.T

### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
torch.max(c)
# Find min
torch.min(c)

torch.max(c),\
torch.min(c)

(tensor(2.5893, device='cuda:0'), tensor(1.6445, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max

torch.argmax(a)
# Find arg min
torch.argmin(a)
torch.argmax(a),\
torch.argmin(a),

(tensor(15, device='cuda:0'), tensor(46, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
torch.manual_seed(7)


# Create random tensor
a = torch.rand(1,1,1,10)


# Remove single dimensions
b = a.squeeze()

# Print out tensors and their shapes
a,a.shape,b,b.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))