In [1]:
import torch 
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt

In [2]:
!nvidia-smi
torch.__version__

Thu Dec  5 19:57:01 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.14                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P5              8W /  114W |     829MiB /   8188MiB |     75%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

'2.5.1+cu124'

In [3]:
f32 =torch.arange(start=100,end=111,dtype=torch.float32)
f16 =torch.arange(start=1000,end=1011,dtype=torch.int64)
type(f32),type(f16),f32.dtype,f16.dtype

(torch.Tensor, torch.Tensor, torch.float32, torch.int64)

In [4]:
i64 = f32.to(torch.int64)
i64.device

device(type='cpu')

In [5]:
t1 = torch.arange(10,20)
t2 = torch.arange(10,20)
t1,t2,t1+t2\
,t1-t2\
,t1*t2\
,t1/t2\
,t1@t2\
,t1&t2\
,t1|t2\
,torch.dot(t1,t2)


(tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 tensor([20, 22, 24, 26, 28, 30, 32, 34, 36, 38]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([100, 121, 144, 169, 196, 225, 256, 289, 324, 361]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor(2185),
 tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 tensor(2185))

In [6]:
M1 = torch.rand(3,3)*10
M2 = torch.rand(3,3)*10
M1 = M1.to(torch.int32)
M2 = M2.to(torch.int32)
M3 = M1@M2;M3 = M3.to(dtype=torch.int64)
M4 = torch.matmul(M1,M2)#torch.matmul == torch.mm
M1,M2,M3,M3.dtype,M4

(tensor([[3, 6, 4],
         [9, 7, 0],
         [5, 6, 1]], dtype=torch.int32),
 tensor([[4, 8, 0],
         [4, 4, 1],
         [7, 9, 8]], dtype=torch.int32),
 tensor([[ 64,  84,  38],
         [ 64, 100,   7],
         [ 51,  73,  14]]),
 torch.int64,
 tensor([[ 64,  84,  38],
         [ 64, 100,   7],
         [ 51,  73,  14]], dtype=torch.int32))

In [7]:
a1 = torch.rand(3,2)
a2 = torch.rand(3,2)
print(a1,a2)
a1 = a1.reshape(a2.shape[1],a2.shape[0])
result = a1 @ a2
result

tensor([[0.8184, 0.5527],
        [0.9757, 0.6765],
        [0.4137, 0.2054]]) tensor([[0.5200, 0.8193],
        [0.7946, 0.9202],
        [0.4375, 0.6406]])


tensor([[1.2916, 1.8042],
        [0.7704, 1.0666]])

In [8]:
M1 = torch.randint(0, 100, (5, 5), dtype=torch.int,device="cpu")
M1

tensor([[83, 41, 47, 32, 78],
        [24, 47,  3, 95, 41],
        [73, 95, 53, 63, 83],
        [44, 91, 24, 64, 89],
        [19, 64, 48, 11, 58]], dtype=torch.int32)

In [9]:
%%time
torch.max(M1)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(95, dtype=torch.int32)

In [10]:
%%time
M1.max

CPU times: total: 0 ns
Wall time: 0 ns


<function Tensor.max>

In [11]:
mean_value = M1.to(dtype=torch.float32).mean().item()
median_value = M1.to(dtype=torch.float32).median().item()
mode_value = M1.to(dtype=torch.float32).mode().values[0].item()

mean_value, median_value, mode_value

(54.79999923706055, 53.0, 32.0)

In [12]:
M1 = torch.randint(0,10,(3,3),dtype=torch.int64)
M1,torch.argmin(M1,dim=0,keepdim=True)

(tensor([[7, 1, 7],
         [3, 1, 4],
         [7, 6, 1]]),
 tensor([[1, 0, 2]]))

In [11]:
import torch
M1 = torch.randint(0,100,(5,5,5), device="cuda")
M1

tensor([[[59, 85, 37, 91, 22],
         [30, 66, 69, 64, 94],
         [87, 82, 87, 78, 82],
         [12, 13,  0, 58, 96],
         [50, 96, 41, 80, 35]],

        [[40,  4, 55, 74, 60],
         [65, 22, 67, 92, 95],
         [26, 82, 50, 54, 26],
         [ 6, 51, 87, 18, 97],
         [22, 45, 27, 93, 27]],

        [[ 4, 92, 88,  9, 87],
         [19, 63,  1, 31, 25],
         [73, 85, 54, 35,  6],
         [15, 65, 52, 52, 27],
         [93, 68, 24, 39, 76]],

        [[58,  4, 53, 26, 20],
         [ 2, 91, 71, 49, 31],
         [96, 93, 11, 48, 35],
         [81, 10, 80, 30, 49],
         [ 3, 54, 19, 44, 17]],

        [[85, 33, 88, 61, 83],
         [92, 15,  4, 52, 46],
         [69, 74, 36, 12, 52],
         [ 3, 43, 50, 75, 66],
         [72,  3, 11, 27, 81]]], device='cuda:0')

In [16]:
M1[2][2][2]

tensor(54, device='cuda:0')

In [15]:
M1[:,:,0]

tensor([[59, 30, 87, 12, 50],
        [40, 65, 26,  6, 22],
        [ 4, 19, 73, 15, 93],
        [58,  2, 96, 81,  3],
        [85, 92, 69,  3, 72]], device='cuda:0')

In [16]:
M1 = torch.randint(0,100,(5,5), device="cuda")
M2 = torch.randint(0,100,(5,5), device="cuda")
M1,M2

(tensor([[91, 59, 55, 99, 85],
         [12,  0, 18, 91,  6],
         [39,  0, 16, 57,  2],
         [93, 68, 42, 66, 26],
         [33, 51, 54, 49, 35]], device='cuda:0'),
 tensor([[50, 28, 78, 88, 34],
         [16, 83, 95, 98, 27],
         [69, 98, 84,  8, 71],
         [64, 22, 37, 39, 52],
         [87, 14, 83,  5, 11]], device='cuda:0'))

In [17]:
M3 = torch.hstack((M1,M2))
M3

tensor([[91, 59, 55, 99, 85, 50, 28, 78, 88, 34],
        [12,  0, 18, 91,  6, 16, 83, 95, 98, 27],
        [39,  0, 16, 57,  2, 69, 98, 84,  8, 71],
        [93, 68, 42, 66, 26, 64, 22, 37, 39, 52],
        [33, 51, 54, 49, 35, 87, 14, 83,  5, 11]], device='cuda:0')

In [18]:
M3 = torch.vstack((M1,M2))
M3,M3.shape

(tensor([[91, 59, 55, 99, 85],
         [12,  0, 18, 91,  6],
         [39,  0, 16, 57,  2],
         [93, 68, 42, 66, 26],
         [33, 51, 54, 49, 35],
         [50, 28, 78, 88, 34],
         [16, 83, 95, 98, 27],
         [69, 98, 84,  8, 71],
         [64, 22, 37, 39, 52],
         [87, 14, 83,  5, 11]], device='cuda:0'),
 torch.Size([10, 5]))

In [19]:
M3 = M3.reshape(5,10)
M3

tensor([[91, 59, 55, 99, 85, 12,  0, 18, 91,  6],
        [39,  0, 16, 57,  2, 93, 68, 42, 66, 26],
        [33, 51, 54, 49, 35, 50, 28, 78, 88, 34],
        [16, 83, 95, 98, 27, 69, 98, 84,  8, 71],
        [64, 22, 37, 39, 52, 87, 14, 83,  5, 11]], device='cuda:0')

In [20]:
M1 = torch.randint(0,100,(2,2,2), device="cuda")
M1

tensor([[[39, 90],
         [77,  4]],

        [[67,  4],
         [57, 14]]], device='cuda:0')

In [21]:
M1.squeeze()

tensor([[[39, 90],
         [77,  4]],

        [[67,  4],
         [57, 14]]], device='cuda:0')

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
t = np.arange(1,10)
M = torch.from_numpy(t)
N = M.numpy()
M,type(N)

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32), numpy.ndarray)

In [72]:
torch.manual_seed(0)
M1 = torch.randint(0,100,(5,5), device="cuda")
torch.manual_seed(0)
M2 = torch.randint(0,100,(5,5), device="cuda")
M1==M2

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]], device='cuda:0')

In [ ]:
import torch
import torch.nn as nn
import numpy as np

class LinearRegression:
    def __init__(self):
        self.model = None
        
    def fit(self, X, y, learning_rate=0.001, epochs=100):
        X = torch.tensor(X, dtype=torch.float32).to(device='cuda')
        y = torch.tensor(y, dtype=torch.float32).view(-1, 1).to(device='cuda')
        
        self.model = nn.Linear(X.shape[1], 1).to(device='cuda')
        
        loss_fn = nn.MSELoss()
        optim = torch.optim.SGD(self.model.parameters(), lr=learning_rate)
        
        for epoch in range(epochs):
            y_pred = self.model(X)
            loss = loss_fn(y_pred, y)
            
            optim.zero_grad()
            loss.backward()
            optim.step()
            
            if (epoch + 1) % 10 == 0:
                print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')
        
    def predict(self, X):
        X = torch.tensor(X, dtype=torch.float32).to(device='cuda')
        with torch.no_grad():
            y_pred = self.model(X)
            
        return y_pred.cpu().numpy()
    
if __name__ == "__main__":
    X = np.array([[1], [2], [3], [4]], dtype=np.float32)  
    y = np.array([1,2,3,4], dtype=np.float32)  
    # np.random.seed(0)
    # X = np.random.rand(100, 1) * 10  
    # y = 3.5 * X.squeeze() + np.random.randn(100) * 0.5 

    regressor = LinearRegression()
    regressor.fit(X, y, epochs=10000, learning_rate=0.01)

    # Make predictions
    X_test = np.array([[100], [103]], dtype=np.float32)
    predictions = regressor.predict(X_test)
    print("Predictions:", predictions)  

Epoch [10/10000], Loss: 0.5988
Epoch [20/10000], Loss: 0.0851
Epoch [30/10000], Loss: 0.0678
Epoch [40/10000], Loss: 0.0635
Epoch [50/10000], Loss: 0.0598
Epoch [60/10000], Loss: 0.0563
Epoch [70/10000], Loss: 0.0530
Epoch [80/10000], Loss: 0.0499
Epoch [90/10000], Loss: 0.0470
Epoch [100/10000], Loss: 0.0443
Epoch [110/10000], Loss: 0.0417
Epoch [120/10000], Loss: 0.0393
Epoch [130/10000], Loss: 0.0370
Epoch [140/10000], Loss: 0.0349
Epoch [150/10000], Loss: 0.0328
Epoch [160/10000], Loss: 0.0309
Epoch [170/10000], Loss: 0.0291
Epoch [180/10000], Loss: 0.0274
Epoch [190/10000], Loss: 0.0258
Epoch [200/10000], Loss: 0.0243
Epoch [210/10000], Loss: 0.0229
Epoch [220/10000], Loss: 0.0216
Epoch [230/10000], Loss: 0.0203
Epoch [240/10000], Loss: 0.0191
Epoch [250/10000], Loss: 0.0180
Epoch [260/10000], Loss: 0.0170
Epoch [270/10000], Loss: 0.0160
Epoch [280/10000], Loss: 0.0151
Epoch [290/10000], Loss: 0.0142
Epoch [300/10000], Loss: 0.0134
Epoch [310/10000], Loss: 0.0126
Epoch [320/10000]

In [21]:
# Make predictions
X_test = np.array([[100], [103]], dtype=np.float32)
predictions = regressor.predict(X_test) 
print("Predictions:", predictions)  

Predictions: [[ 99.99989 ]
 [102.999886]]


In [29]:
6//-132
abs(-132)>abs(6),abs(6)//abs(-132)

(True, 0)