In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
!nvidia-smi
torch.__version__

Mon Apr 28 00:43:16 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0             14W /   80W |     580MiB /   8188MiB |      8%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

'2.6.0+cu124'

In [4]:
#scalar
a = torch.tensor(7)

a,a.ndim,type(a),type(a.item())

(tensor(7), 0, torch.Tensor, int)

In [5]:
#Vector

c = torch.tensor([1,2,3])
M2 = torch.tensor( [[1,2],[3,4]])
M3 = torch.tensor([[[1,2],
                    [3,4]]])

c,M2,M3,type(c),c.ndim,type(M2),M2.shape,M2.ndim,type(M3),M3.ndim,M3.shape

(tensor([1, 2, 3]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[[1, 2],
          [3, 4]]]),
 torch.Tensor,
 1,
 torch.Tensor,
 torch.Size([2, 2]),
 2,
 torch.Tensor,
 3,
 torch.Size([1, 2, 2]))

In [13]:
M1 = torch.rand(3,3)
M2 = torch.zeros(1,2,2)
M3 = torch.ones(1,2,3)
M1,M2,M3



(tensor([[0.0978, 0.6472, 0.6874],
         [0.0379, 0.7508, 0.6820],
         [0.9251, 0.3261, 0.0281]]),
 tensor([[[0., 0.],
          [0., 0.]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.]]]))

In [14]:
M1[1::,0]= 0
M1 

tensor([[0.0978, 0.6472, 0.6874],
        [0.0000, 0.7508, 0.6820],
        [0.0000, 0.3261, 0.0281]])

In [15]:
R = torch.arange(1,11)
R

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
R2 = torch.arange(start=0, end=10,dtype=torch.int)
R2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [17]:
R1 = torch.tensor([torch.rand(1) for x in range(10)],dtype=torch.double)
ZR1 = torch.zeros_like(R1)
R1,ZR1

(tensor([0.2560, 0.2958, 0.6848, 0.8137, 0.4114, 0.5171, 0.1718, 0.5385, 0.0185,
         0.9724], dtype=torch.float64),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64))

In [17]:
T1 = torch.tensor(torch.arange(10),
                  requires_grad=False,
                  dtype=torch.double,
                  device='cpu')
T1

C:\Users\Harish K B\AppData\Local\Temp\ipykernel_23364\2046787710.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  T1 = torch.tensor(torch.arange(10),


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [19]:
f32 =torch.arange(start=100,end=111,dtype=torch.float32)
f16 =torch.arange(start=1000,end=1011,dtype=torch.int64)
type(f32),type(f16),f32.dtype,f16.dtype

(torch.Tensor, torch.Tensor, torch.float32, torch.int64)

In [20]:
i64 = f32.to(torch.int64)

In [21]:
type(f32),type(f16),f32.dtype,f16.dtype


(torch.Tensor, torch.Tensor, torch.float32, torch.int64)

In [9]:
# Tensor Creation
# Create a 2x3 tensor filled with ones.

one = torch.ones(size=(2,3))


# Create a tensor of shape (4, 4) with random values between 0 and 1.

two = torch.rand(size=(4,4))

# Generate a 3x3 identity matrix.

three = torch.eye(n=5)

# Create a tensor of integers from 10 to 50 with a step of 5.

four = torch.arange(10,50,5)

# Create a tensor of shape (2, 3) and then convert it to a float tensor.

five = torch.rand(size=(2,3)); five = five.to(torch.float32)


one,two,three,four,five,five.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0.6033, 0.4480, 0.5502, 0.2143],
         [0.1198, 0.5370, 0.7507, 0.0363],
         [0.6728, 0.9272, 0.0539, 0.1182],
         [0.2703, 0.1317, 0.8682, 0.5924]]),
 tensor([[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]]),
 tensor([10, 15, 20, 25, 30, 35, 40, 45]),
 tensor([[0.3250, 0.8955, 0.1694],
         [0.9157, 0.8865, 0.4794]]),
 torch.float32)

In [35]:
# Basic Manipulations
# Reshape a tensor of shape (4, 2) into (2, 4).

one = torch.rand((4,2))
# print(one.shape)

one = one.reshape((2,4))
# print(one.shape)


# Concatenate two tensors of shape (2, 3) along the second dimension.


two1 = torch.rand((4,2))
two2 = torch.rand((4,2))

two = torch.cat((two1,two2),dim=1)



# Stack three tensors of shape (2, 2) along a new dimension.

three1 = torch.rand((2,2))
three2 = torch.rand((2,2))
three3 = torch.rand((2,2))

three = torch.stack((three1,three2,three3),dim=0)


# Slice a 4x4 tensor to extract a 2x2 sub-tensor from the center.

four1 = torch.rand((4,4))

print(four1)
four = four1[1:3,1:3]
print(four)
# Create a tensor and compute its transpose.

five = torch.rand((4,2))
print(five.T)


tensor([[0.7383, 0.0737, 0.5742, 0.2597],
        [0.7981, 0.1443, 0.0092, 0.5502],
        [0.3813, 0.1551, 0.9342, 0.6405],
        [0.0421, 0.7905, 0.2509, 0.1503]])
tensor([[0.1443, 0.0092],
        [0.1551, 0.9342]])
tensor([[0.0549, 0.7849, 0.1161, 0.5049],
        [0.8501, 0.6585, 0.5292, 0.3978]])


In [46]:
# Advanced Manipulations
# Create a tensor of shape (3, 3) and set the diagonal elements to 1 and all other elements to 0.

one1 = torch.rand((3,3))

print(one1)
mask = ~torch.eye(3,dtype=torch.bool)

one1[mask]=1
one1.fill_diagonal_(0)

print(one1,~torch.eye(3,dtype=torch.bool))

# Generate a tensor of shape (3, 3) and normalize its values to the range [0, 1].

# Perform element-wise multiplication of two tensors of shape (3, 3).

# Replace all values in a tensor greater than 0.5 with the value 1.

# Compute the dot product of two 1D tensors.

tensor([[0.5179, 0.0833, 0.8855],
        [0.7494, 0.0493, 0.9736],
        [0.6921, 0.6094, 0.4027]])
tensor([[0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 0.]]) tensor([[False,  True,  True],
        [ True, False,  True],
        [ True,  True, False]])
