In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
!nvidia-smi
torch.__version__

Wed Jan 29 19:36:38 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.14                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8              1W /   80W |     182MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

'2.5.1+cu124'

In [4]:
#scalar
a = torch.tensor(7)

a,a.ndim,type(a),type(a.item())

(tensor(7), 0, torch.Tensor, int)

In [5]:
#Vector

c = torch.tensor([1,2,3])
M2 = torch.tensor( [[1,2],[3,4]])
M3 = torch.tensor([[[1,2],
                    [3,4]]])

c,M2,M3,type(c),c.ndim,type(M2),M2.shape,M2.ndim,type(M3),M3.ndim,M3.shape

(tensor([1, 2, 3]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[[1, 2],
          [3, 4]]]),
 torch.Tensor,
 1,
 torch.Tensor,
 torch.Size([2, 2]),
 2,
 torch.Tensor,
 3,
 torch.Size([1, 2, 2]))

In [13]:
M1 = torch.rand(3,3)
M2 = torch.zeros(1,2,2)
M3 = torch.ones(1,2,3)
M1,M2,M3



(tensor([[0.0978, 0.6472, 0.6874],
         [0.0379, 0.7508, 0.6820],
         [0.9251, 0.3261, 0.0281]]),
 tensor([[[0., 0.],
          [0., 0.]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.]]]))

In [14]:
M1[1::,0]= 0
M1 

tensor([[0.0978, 0.6472, 0.6874],
        [0.0000, 0.7508, 0.6820],
        [0.0000, 0.3261, 0.0281]])

In [15]:
R = torch.arange(1,11)
R

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
R2 = torch.arange(start=0, end=10,dtype=torch.int)
R2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [17]:
R1 = torch.tensor([torch.rand(1) for x in range(10)],dtype=torch.double)
ZR1 = torch.zeros_like(R1)
R1,ZR1

(tensor([0.2560, 0.2958, 0.6848, 0.8137, 0.4114, 0.5171, 0.1718, 0.5385, 0.0185,
         0.9724], dtype=torch.float64),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64))

In [17]:
T1 = torch.tensor(torch.arange(10),
                  requires_grad=False,
                  dtype=torch.double,
                  device='cpu')
T1

C:\Users\Harish K B\AppData\Local\Temp\ipykernel_23364\2046787710.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  T1 = torch.tensor(torch.arange(10),


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [19]:
f32 =torch.arange(start=100,end=111,dtype=torch.float32)
f16 =torch.arange(start=1000,end=1011,dtype=torch.int64)
type(f32),type(f16),f32.dtype,f16.dtype

(torch.Tensor, torch.Tensor, torch.float32, torch.int64)

In [20]:
i64 = f32.to(torch.int64)

In [21]:
type(f32),type(f16),f32.dtype,f16.dtype


(torch.Tensor, torch.Tensor, torch.float32, torch.int64)