In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
!nvidia-smi
torch.__version__

Thu Dec  5 18:11:00 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.14                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8              1W /  115W |     232MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

'2.4.1+cpu'

In [3]:
#scalar
a = torch.tensor(7)

a,a.ndim,type(a),type(a.item())

(tensor(7), 0, torch.Tensor, int)

In [4]:
#Vector

c = torch.tensor([1,2,3])
M2 = torch.tensor( [[1,2],[3,4]])
M3 = torch.tensor([[[1,2],
                    [3,4]]])
type(c),c.ndim,type(M2),M2.shape,M2.ndim,type(M3),M3.ndim,M3.shape

(torch.Tensor,
 1,
 torch.Tensor,
 torch.Size([2, 2]),
 2,
 torch.Tensor,
 3,
 torch.Size([1, 2, 2]))

In [12]:
M1 = torch.rand(3,3)
M2 = torch.zeros(1,2,2)
M3 = torch.ones(1,2,3)
M1,M2,M3



(tensor([[0.2744, 0.2220, 0.3442],
         [0.8354, 0.5701, 0.3845],
         [0.6180, 0.0723, 0.6142]]),
 tensor([[[0., 0.],
          [0., 0.]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.]]]))

In [13]:
M1[::,0]= 0
M1 

tensor([[0.0000, 0.2220, 0.3442],
        [0.0000, 0.5701, 0.3845],
        [0.0000, 0.0723, 0.6142]])

In [14]:
R = torch.arange(1,11)
R

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
R2 = torch.arange(start=0, end=10,dtype=torch.int)
R2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [16]:
R1 = torch.tensor([torch.rand(1) for x in range(10)],dtype=torch.double)
ZR1 = torch.zeros_like(R1)
R1,ZR1

(tensor([0.1516, 0.2632, 0.3968, 0.8617, 0.3222, 0.6523, 0.3065, 0.5903, 0.7937,
         0.7140], dtype=torch.float64),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64))

In [17]:
T1 = torch.tensor(torch.arange(10),
                  requires_grad=False,
                  dtype=torch.double,
                  device='cpu')
T1

C:\Users\Harish K B\AppData\Local\Temp\ipykernel_23364\2046787710.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  T1 = torch.tensor(torch.arange(10),


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [32]:
f32 =torch.arange(start=100,end=111,dtype=torch.float32)
f16 =torch.arange(start=1000,end=1011,dtype=torch.int64)
type(f32),type(f16),f32.dtype,f16.dtype

(torch.Tensor, torch.Tensor, torch.float32, torch.int64)

In [33]:
i64 = f32.to(torch.int64)

In [34]:
type(f32),type(f16),f32.dtype,f16.dtype


(torch.Tensor, torch.Tensor, torch.float32, torch.int64)